Document: amxa-offline-folders
Title: Debian amxa-offline-folders Manual
Author: <insert document author here>
Abstract: This manual describes what amxa-offline-folders is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/amxa-offline-folders/amxa-offline-folders.sgml.gz

Format: postscript
Files: /usr/share/doc/amxa-offline-folders/amxa-offline-folders.ps.gz

Format: text
Files: /usr/share/doc/amxa-offline-folders/amxa-offline-folders.text.gz

Format: HTML
Index: /usr/share/doc/amxa-offline-folders/html/index.html
Files: /usr/share/doc/amxa-offline-folders/html/*.html
